version: "3.2"
services:
  postgres:
    image: postgres:latest
    # ports:
    #   - "5430:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=simplesso 
  redis:
    image: "redis"
    command: redis-server --save "" --appendonly no
    ports:
      - "6379:6379"
    
  simple_sso:
    image: golang:1.18
    volumes:
      - .:/etc/simple_sso
    working_dir: /etc/simple_sso
    ports:
      - "8080:8080"
    environment:
      - POSTGRES__PORT=5432
      - POSTGRES__HOST=postgres 
      - POSTGRES__USER=postgres
      - POSTGRES__PASSWORD=postgres
      - POSTGRES__DBNAME=simplesso
      - MIGRATION__PORT=5432
      - MIGRATION__HOST=postgres 
      - MIGRATION__USER=postgres
      - MIGRATION__PASSWORD=postgres
      - MIGRATION__DBNAME=simplesso
      - REDIS__HOST=redis
      - REDIS__PORT=6379
    depends_on:
            - postgres
            - redis
    command: >
      sh -c "go run ." 